

[workspace]
members = [ 
    "rendering-engine", 
    "monorepo/hello-wasm",
    "monorepo/paint-wasm",
    "monorepo/infinite-paint-wasm",
    "monorepo/macro-cosmos",
]


[profile.release]
opt-level = "s"
