

[workspace]
members = [ 
    "rendering-engine", 
    "rust-packages/hello-wasm",
    "rust-packages/paint-wasm",
    "rust-packages/infinite-paint-wasm",
    "rust-packages/macro-cosmos",
]


[profile.release]
opt-level = "s"
