

[workspace]
members = [ 
    "rendering-engine", 
    "rust-packages/hello-wasm",
    "rust-packages/paint-wasm",
    "rust-packages/infinite-paint-wasm"
, "rust-packages/neo-space-000"]


[profile.release]
opt-level = "s"
