

[workspace]
members = [ 
    "rendering-engine", 
    "rust-packages/hello-wasm",
    "rust-packages/tiny-neo-space",
    "rust-packages/paint-wasm",
    "rust-packages/infinite-paint-wasm"
]


[profile.release]
opt-level = "s"
